<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
/* genesis(); */
get_header();  ?>

<div class="custom_single_post_page">

    <div class="container">
        <div class="row">
            <div class="post-content-left">
                    <h1 class="post-title">Kurse für junge Mütter</h1>
                    <h5 class="post-author">von MAria K.</h5>
                    <p class="post-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur.</p>

                    <p class="post-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur  elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua incididunt ut labore.</p>
            </div>
            <div class="post-content-right">
                <div class="vote-counter">29</div>
                <div class="vote-counter-subtext">STimmen</div>
                <button class="custom-button">Jetzt abstimmen</button>
            </div>
        </div>
    </div>
</div>

<?php
get_footer();
?>